# Supported Funding Model Platforms
# ---------------------------------
#
# This section of the code specifies the supported funding model platforms for the developer.
# Currently, Patreon and GitHub Sponsors are supported.
#
# Format:
#   [platform]: [username]
#
# Example:
#   patreon: eduardopires
#   github_sponsors: [username]

patreon: eduardopires
github_sponsors: [githubusername]

