/// <summary>
/// The Equinox Project is a full ASP.NET Core 3.1 application that demonstrates the implementation of Domain-Driven Design (DDD), Command Query Responsibility Segregation (CQRS), and Event Sourcing.
/// </summary>

/// <summary>
/// This Jekyll configuration file sets up the Equinox Project's documentation site.
/// </summary>
/// <remarks>
/// The file specifies the theme, gems, and other settings for the site.
/// </remarks>

/// <summary>
/// The 'jekyll-mentions' gem is included to enable the use of @mentions in the documentation.
/// </summary>

